people/urls.py
from django.conf.urls import url
from people import views

urlpatterns = [
    url(r'^$', views.index, name='people.index'),
    url(r'^person/(?P<person_id>\d+)/$', views.person, name='person'),
    url(r'^person/(?P<person_id>\d+)/edit/$', views.edit_person, name='edit_person'),
    url(r'^person/(?P<person_id>\d+)/photo/$', views.add_person_photo, name='photo'),
    url(r'^person/(?P<person_id>\d+)/relatives/$', views.relatives, name='relatives'),
    url(r'^person/(?P<person_id>\d+)/relatives/map/$', views.relatives_map, name='relatives_map'),
    url(r'^person/(?P<person_id>\d+)/descendants/$', views.descendants, name='descendants'),
    url(r'^person/(?P<person_id>\d+)/descendants/map/$', views.descendants_map, name='descendants_map'),
    url(r'^person/(?P<person_id>\d+)/descendants/tree/$', views.descendants_tree, name='descendants_tree'),
    url(r'^person/(?P<person_id>\d+)/descendants/tree/svg/$', views.descendants_tree_svg, name='descendants_tree_svg'),
    url(r'^person/(?P<person_id>\d+)/ancestors/$', views.ancestors, name='ancestors'),
    url(r'^person/(?P<person_id>\d+)/ancestors/report/$', views.ancestors_report, name='report'),
    url(r'^person/(?P<person_id>\d+)/ancestors/report/undead/$',
        views.ancestors_report_undead,
        name='report_undead'),
    url(r'^person/(?P<person_id>\d+)/ancestors/report/maiden-names/$',
        views.ancestors_report_maiden_names,
        name='report_maiden_names'),
    url(r'^report/alive/(?P<year>\d+)/$', views.alive_in_year, name='alive_in_year'),
    url(r'^person/(?P<person_id>\d+)/ancestors/map/$', views.ancestors_map, name='ancestors_map'),
    url(r'^person/(?P<person_id>\d+)/ancestors/ringchart/$', views.ring_chart, name='ring_chart'),
    url(r'^person/(?P<person_id>\d+)/ancestors/treechart/$', views.family_tree_chart, name='tree_chart'),
    url(r'^person/(?P<person_id>\d+)/ancestors/ringchart/svg/$', views.ring_chart_svg, name='ring_chart_svg'),
    url(r'^location/(?P<location_id>\d+)/$', views.location, name='location'),
    url(r'^region/(?P<region_name>[\w\W]+)/$', views.region, name='region'),
    url(r'^surname/(?P<surname>[\w\W]+)/$', views.surname, name='surname'),
    url(r'^forename/(?P<forename>[\w\W]+)/$', views.forename, name='forename'),
    url(r'^tag/(?P<slug>[\w-]+)/$', views.tag, name='tag'),
    url(r'^person/add/$', views.add_person, name='add_person'),
    url(r'^location/add/$', views.add_location, name='add_location'),

    url(r'^public/surnames/$', views.surnames, name='surnames'),
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
import django.views.static
import django.contrib.auth.views
import os.path
import settings

urlpatterns = [
    url(r'', include('people.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^login/$', django.contrib.auth.views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': '/'}, name='logout'),
]

# Get Django to serve media files in debug mode.
if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
                        django.views.static.serve,
                        {'document_root': settings.MEDIA_ROOT})]

admin.site.site_header = 'Family Tree Peter'
admin.site.site_title = 'Family Tree Peter'
admin.site.index_title = 'Family Tree Peter'

people/models.py
from datetime import date
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Count, Q
from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver
from itertools import chain
from opencage.geocoder import OpenCageGeocode
from operator import attrgetter
from people.fields import UncertainDateField
from people.relations import closest_common_ancestor, describe_relative
from taggit.managers import TaggableManager
from taggit.models import Tag, TaggedItem
from tinymce.models import HTMLField
import os
import settings
from people.helpers import renameUploadedFile

class Country(models.Model):
    name = models.CharField(max_length=50)
    country_code = models.CharField(max_length=3)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'countries'


class Location(models.Model):
    '''A location is not meant to be a pinpoint address but a general place such
    as a town or village.'''
    name = models.CharField(max_length=50, help_text='Place name')
    county_state_province = models.CharField(max_length=30,
                                             verbose_name='county/state/province',
                                             help_text='County / state / province')
    country = models.ForeignKey(Country, help_text='Country')
    # If left blank, these fields will be set by geocoding when the model is
    # saved.
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not (self.latitude and self.longitude):
            try:
                geocoder = OpenCageGeocode(settings.OPENCAGE_API_KEY)
                query = '{0}, {1}, {2}'.format(self.name,
                                               self.county_state_province,
                                               self.country.name)
                result = geocoder.geocode(query)
                geometry = result[0].get('geometry')
                self.latitude = geometry.get('lat')
                self.longitude = geometry.get('lng')
            except Exception as e:
                # If something goes wrong, there's not much we can do, just leave
                # the coordinates blank.
                print (e)
        super(Location, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('location', args=[self.id])

    def __str__(self):
        return '{0}, {1}'.format(self.name, self.county_state_province)

    def __eq__(self, other):
        if other:
            return self.name == other.name and self.latitude == other.latitude and self.longitude == other.longitude
        else:
            return False

    def __hash__(self):
        return hash(self.name) + hash(self.latitude) + hash(self.longitude)

    class Meta:
        ordering = ['country', 'county_state_province', 'name']
        unique_together = [('country', 'county_state_province', 'name')]


class Person(models.Model):
    '''The main class of the model. Every individual is represented by a person
    record.'''
    forename = models.CharField(max_length=20, help_text='Forename / given name')
    middle_names = models.CharField(blank=True, max_length=50, help_text='Middle names(s)')
    known_as = models.CharField(blank=True, max_length=20, help_text='Known as')
    surname = models.CharField(max_length=30, help_text='Surname')
    maiden_name = models.CharField(blank=True, max_length=30, help_text='Maiden name') # Maiden name is optional.
    gender = models.CharField(max_length=1,
                              choices=(('M', 'Male'), ('F', 'Female')),
                              blank=False,
                              default=None)
    birth = models.ForeignKey('Event', models.SET_NULL, null=True, blank=True, related_name='+')
    death = models.ForeignKey('Event', models.SET_NULL, null=True, blank=True, related_name='+')
    deceased = models.BooleanField(default=True)
    blood_relative = models.BooleanField(default=True)
    mother = models.ForeignKey('self',
                               blank=True,
                               null=True,
                               limit_choices_to={'gender': 'F'},
                               related_name='children_of_mother',
                               on_delete=models.SET_NULL)
    father = models.ForeignKey('self',
                               blank=True,
                               null=True,
                               limit_choices_to={'gender': 'M'},
                               related_name='children_of_father',
                               on_delete=models.SET_NULL)
    notes = HTMLField(blank=True)
    tags = TaggableManager(blank=True, help_text='Tags')
    # A person can be linked to a user account. This allows a user to see
    # information relevant to their own relationships.

    user = models.OneToOneField(User, blank=True, null=True)

    avatar = models.ImageField(upload_to=renameUploadedFile('avatar'), null=True, blank=True,help_text='Avatar Image')



    def name(self, use_middle_names=True, use_maiden_name=False):
        '''Returns the full name of this person.'''
        name = ' '.join([self.forename, self.middle_names]) if use_middle_names and self.middle_names else self.forename
        if self.known_as:
            name = name + ' "{0}"'.format(self.known_as)
        if self.maiden_name != '':
            return name + ' ' + (self.maiden_name if use_maiden_name else self.surname.upper() + u' (n\xe9e ' + self.maiden_name + ')')
        else:
            return name + ' ' + self.surname.upper()

    def given_names(self):
        return " ".join([self.forename, self.middle_names]) if self.middle_names else self.forename

    def birth_surname(self):
        return self.maiden_name if self.maiden_name else self.surname

    def birth_name(self):
        return '{0} {1}'.format(self.given_names(), self.birth_surname().upper())

    def date_of_birth(self):
        return self.birth.date if self.birth else None

    def birth_location(self):
        return self.birth.location if self.birth else None

    def date_of_death(self):
        return self.death.date if self.death else None

    def age(self):
        '''Calculate the person's age in years.'''
        if not self.date_of_birth() or (self.deceased and not self.date_of_death()):
            return None
        end = self.date_of_death() if self.deceased else date.today()
        years = end.year - self.date_of_birth().year
        if end.month and self.date_of_birth().month:
            if end.month < self.date_of_birth().month \
               or (end.month == self.date_of_birth().month \
                   and end.day and self.date_of_birth().day and end.day < self.date_of_birth().day):
                years -= 1
        return years

    def year_range(self):
        return '{0}-{1}'.format(self.date_of_birth().year if self.date_of_birth() else '????',
                                '' if not self.deceased else self.date_of_death().year if self.date_of_death() else '????')

    def spouses(self):
        '''Return a list of anybody that this person is or was married to.'''
        if self.gender == 'F':
            return [(m.husband, m.date, m.location, m.divorced) for m in self.wife_of.all()]
        else:
            return [(m.wife, m.date, m.location, m.divorced) for m in self.husband_of.all()]

    def siblings(self):
        '''Returns a list of this person's brothers and sisters, including
        half-siblings.'''
        return Person.objects.filter(~Q(id=self.id),
                                     Q(~Q(father=None), father=self.father) | \
                                     Q(~Q(mother=None), mother=self.mother)).order_by('birth__date')

    def children(self):
        '''Returns a list of this person's children.'''
        offspring = self.children_of_mother if self.gender == 'F' else self.children_of_father
        return offspring.select_related('birth', 'death').order_by('birth__date')

    def marriages(self):
        return self.husband_of.all() if self.gender == 'M' else self.wife_of.all()

    def timeline(self):
        timeline = list(self.events.all()) + list(self.marriages().filter(date__isnull=False))
        timeline.sort(key=attrgetter('date'))
        timeline.sort(key=attrgetter('event_type'))
        return timeline

    def _descendant_distances(self, offset=0):
        descendants = {}
        for child in self.children():
            descendants[child] = offset + 1
            descendants.update(child._descendant_distances(offset + 1))
        return descendants

    def descendants(self):
        '''Returns a list of this person's descendants (their children and all
        of their children's descendants).'''
        for child in self.children():
            yield child
            yield from child.descendants()

    def annotated_descendants(self):
        '''Returns a list of this person's descendants annotated with the name
        of the relationship to this person (so a list of (Person, relationship)
        tuples.'''
        distances = self._descendant_distances()
        descendants = []
        for descendant in distances.keys():
            relationship = describe_relative(self, descendant, {}, descendant._ancestor_distances())
            descendants.append((descendant, relationship, distances[descendant]))
        descendants.sort(key=lambda x: (x[2], x[1], x[0].surname))
        return descendants


    def annotated_descendants2(self):
        '''Returns a list of this person's descendants annotated with the name
        of the relationship to this person and distance. Suitable for d3.js tree charts'''
        distances = self._descendant_distances()
        descendants = []

people/templates/people/add.html
{% extends "people/base.html" %}
{% load static %}
{% block title %}Add Person{% endblock %}
{% block head %}
  {{ form.media }}
  <script src="{% static 'people/js/bootstrap-tagsinput.min.js' %}"></script>
  <link href="{% static 'people/css/bootstrap-tagsinput.css' %}" rel="stylesheet" />
  <style>.select2-container, .bootstrap-tagsinput {width: 100% !important;}</style>
{% endblock %}

{% block content %}
  {% include 'people/fragments/addlocation.html' %}
  <h1 class="page-header">{% block heading %}Add Person{% endblock %}</h1>
  <div class="row">
    <div class="col-md-12">
      {% if form.non_field_errors %}
        <div class="alert alert-danger">
          {% for error in form.non_field_errors %}
            {{ error }}<br/>
          {% endfor %}
        </div>
      {% endif %}
      <form method="post" role="form" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="well">
          <fieldset>
            <div class="row">
              <div class="form-group col-md-6{% if form.gender.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.gender.label }}</label>
                {% for radio in form.gender %}
                  <div class="radio-inline">
                    {{ radio.tag }} {{ radio.choice_label }}
                  </div>
                {% endfor %}
              </div>
              <div class="form-group col-md-6 text-right">
                <div class="checkbox-inline">
                  {{ form.blood_relative }} {{ form.blood_relative.label }}
                </div>
                <div class="checkbox-inline">
                  {{ form.deceased }} {{ form.deceased.label }}
                </div>
              </div>
            </div>
          </fieldset>

          <fieldset>
            <legend>Name</legend>
            <div class="row">
              <div class="form-group col-md-3{% if form.forename.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.forename.label }}</label>
                {{ form.forename }}
              </div>
              <div class="form-group col-md-5{% if form.middle_names.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.middle_names.label }}</label>
                {{ form.middle_names }}
              </div>
              <div class="form-group col-md-4{% if form.surname.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.surname.label }}</label>
                {{ form.surname }}
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-3{% if form.known_as.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.known_as.label }}</label>
                {{ form.known_as }}
              </div>
              <div class="form-group col-md-4 col-md-offset-5{% if form.maiden_name.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.maiden_name.label }}</label>
                {{ form.maiden_name }}
              </div>
            </div>
          </fieldset>
        </div>

        <div class="row">

        <div class="col-md-12">
         <div class="form-group col-md-4 col-md-offset-5{% if form.avatar.errors %} has-error{% endif %}">
                <label class="control-label sr-only">{{ form.avatar.label }}</label>
                {{ form.avatar }}
              </div>

        </div>


        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="well">
              <fieldset>
                <legend>Birth</legend>
                {% include 'people/fragments/eventfields.html' with event='birth' date=form.date_of_birth location=form.birth_location reference=form.birth_reference %}
                {% include 'people/fragments/eventfields.html' with event='baptism' date=form.date_of_baptism location=form.baptism_location reference=form.baptism_reference %}
              </fieldset>
            </div>
          </div>

          <div class="col-md-6">
            <div class="well">
              <fieldset id="death">
                <legend>Death</legend>
                {% include 'people/fragments/eventfields.html' with event='death' date=form.date_of_death location=form.death_location reference=form.death_reference %}
                {% include 'people/fragments/eventfields.html' with event='burial' date=form.date_of_burial location=form.burial_location reference=form.burial_reference %}
              </fieldset>
            </div>
          </div>
        </div>

        <div class="well">
          <fieldset>
            <legend>Parents</legend>
            <div class="row">
              <div class="form-group col-md-6">
                <label class="control-label sr-only">{{ form.mother.label }}</label>
                {{ form.mother }}
              </div>
              <div class="form-group col-md-6">
                <label class="control-label sr-only">{{ form.father.label }}</label>
                {{ form.father }}
              </div>
            </div>
          </fieldset>
        </div>

        <div class="well">
          <fieldset>
            <legend>Notes</legend>
            {{ form.notes }}<br/>
            {{ form.tags }}
          </fieldset>
        </div>

        <div class="text-right">
          <button type="submit" class="btn btn-primary">{% block button_title %}Add Person{% endblock %}</button>
        </div>
      </form>
    </div>
  </div>
  <script>
    $(document).ready(function(){
      $('#death, #id_death_location, #id_burial_location').prop('disabled', !$('#id_deceased').is(':checked'));
      $('#id_maiden_name').prop('disabled', !$('#id_gender_1').prop('checked'));
      $('#id_birth_location').select2({templateResult: placeTemplate, templateSelection: placeTemplate, placeholder: 'Birthplace'});
      $('#id_baptism_location').select2({templateResult: placeTemplate, templateSelection: placeTemplate, placeholder: 'Location'});
      $('#id_death_location').select2({templateResult: placeTemplate, templateSelection: placeTemplate, placeholder: 'Location'});
      $('#id_burial_location').select2({templateResult: placeTemplate, templateSelection: placeTemplate, placeholder: 'Location'});
      $('#id_mother').select2({templateResult: nameTemplate, templateSelection: nameTemplate, placeholder: 'Mother'});
      $('#id_father').select2({templateResult: nameTemplate, templateSelection: nameTemplate, placeholder: 'Father'});
      $('#id_deceased').on('change', function(){$('#death, #id_death_location, #id_burial_location').prop('disabled', !$(this).is(':checked'));});
      $('.radio-inline').on('change', function(){$('#id_maiden_name').prop('disabled', !$('#id_gender_1').prop('checked'));});
      $('#id_tags').tagsinput({tagClass: function(item){return 'label label-primary';}, trimValue: true});
    });
  </script>
{% endblock %}

people/templates/people/base.html
{% load static %}
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.6/select2-bootstrap.min.css" rel="stylesheet" />
    <link href="{% static 'people/css/people.css' %}" rel="stylesheet" />
    <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{% static 'people/js/dropdowns.js' %}"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% block navbar %}{% include 'people/fragments/navbar.html' %}{% endblock %}
    {% block header %}{% endblock %}
    {% block container %}
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
    <p>This is prototype application for Peter. For technical assistance, hit me up at kmsium@gmail.com or telegram messenger: @solohairy</p>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

people/templates/people/edit.html
{% extends "people/add.html" %}
{% block title %}Edit {{ form.instance.name }}{% endblock %}
{% block heading %}Edit {{ form.instance.name }}{% endblock %}
{% block button_title %}Save{% endblock %}

people/templates/people/index.html
{% extends "people/base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}Family Tree - Overview{% endblock %}
{% block head %}
  {% include 'people/fragments/mapresources.html' with clustering=True fullscreen=True %}
  <script src="{% static 'people/js/jquery.tagcloud.js' %}"></script>
  <style>
    .tab-pane tbody>tr:first-child>td {border-top: 0;}
    #map {height: 400px;}
    .marker-simple div {background-color: #325d88; opacity: 0.84; color: #fff; width: 24px; height: 24px; margin: 12px 0 0 12px;}
    .marker-simple small {line-height: 24px;}
    a sup {display: inline-block; text-decoration: none;}
  </style>
{% endblock %}

{% block content %}
  <br/>
  <div class="row">
    <div class="col-md-8">
      <div class="panel-group">
        {% include 'people/fragments/clouds.html' %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Map of Birthplaces</h3>
          </div>
          {% include 'people/fragments/map.html' with zoom=6 %}
        </div>
      </div>
    </div>
    <div class="col-md-4">
      {% include 'people/fragments/accordion.html' %}
    </div>
  </div>
{% endblock %}

people/templates/people/location.html
{% extends "people/base.html" %}
{% load static %}
{% block title %}{{ location }}{% endblock %}
{% block head %}
  {% include 'people/fragments/mapresources.html' with clustering=False fullscreen=True %}
  <style>
    .headerSortUp:after {content: " \25bc"}
    .headerSortDown:after {content: " \25b2"}
    .text-muted a {color: inherit;}
    #map {height: 300px; padding: 0; margin-top: -10px;}
  </style>
  <script src="{% static 'people/js/jquery.tablesorter.min.js' %}"></script>
  <script src="{% static 'people/js/tablesorterextra.js' %}"></script>
  <script>
    $(document).ready(function(){
      {% if births %}
        $("#births-table").tablesorter({sortList: [[0,0]],
                                        headers: {1: {sorter: "names"}, 2: {sorter: "names"}, 3: {sorter: "names"}, 4: {sorter: false}},
                                        textExtraction: getSortValue});
      {% endif %}
      {% if marriages %}
        $("#marriages-table").tablesorter({sortList: [[0,0]],
                                           headers: {1: {sorter: "names"}, 2: {sorter: "names"}},
                                           textExtraction: getSortValue});
      {% endif %}
      {% if deaths %}
        $("#deaths-table").tablesorter({sortList: [[0,0]],
                                        headers: {1: {sorter: "names"}, 4: {sorter: false}},
                                        textExtraction: getSortValue});
      {% endif %}
    });
  </script>
{% endblock %}

{% block header %}
  {% include 'people/fragments/map.html' with zoom=14 %}
{% endblock %}

{% block content %}
  <h1 class="page-header">
    <img src="{% get_static_prefix %}people/images/flags/large/{{ location.country.country_code }}.png"
         alt="{{ location.country }}" class="flag-large" />
    {{ location.name }} <small>{{ location.county_state_province }}</small>
  </h1>
  <ul class="nav nav-tabs nav-justified">
    {% if births %}
      <li class="active"><a href="#births" data-toggle="tab">Births <span class="badge">{{ births|length }}</span></a></li>
    {% else %}
      <li class="disabled"><a href="#births">Births</span></a></li>
    {% endif %}

    {% if marriages %}
      <li{% if not births %} class="active"{% endif %}><a href="#marriages" data-toggle="tab">Marriages <span class="badge">{{ marriages|length }}</span></a></li>
    {% else %}
      <li class="disabled"><a href="#marriages">Marriages</span></a></li>
    {% endif %}

    {% if deaths %}
      <li{% if not births and not marriages %} class="active"{% endif %}><a href="#deaths" data-toggle="tab">Deaths <span class="badge">{{ deaths|length }}</span></a></li>
    {% else %}
      <li class="disabled"><a href="#deaths">Deaths</a></li>
    {% endif %}
  </ul>
  <br/>
  <div class="tab-content">
    <div class="tab-pane{% if births %} active{% endif %}" id="births">
      <table class="table" id="births-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Name</th>
            <th class=hidden-xs">Mother</th>
            <th class=hidden-xs">Father</th>
            <th class="hidden-xs">&nbsp;</th>
          </tr>
        </thead>
        <tbody>
        {% for person in births %}
          <tr class="{% if not person.blood_relative %}text-muted small{% endif %}">
            <td data-sort-value="{{ person.date_of_birth.lower_bound|date:'Y-m-d' }}">{{ person.date_of_birth.short }}</td>
            <td>
              <a href="{% url 'person' person.id %}">{{ person.name }}</a>
            </td>
            <td class=hidden-xs">
              {% if person.mother %}<a href="{% url 'person' person.mother.id %}">{{ person.mother.name }}</a>{% endif %}
            </td>
            <td class=hidden-xs">
              {% if person.father %}<a href="{% url 'person' person.father.id %}">{{ person.father.name }}</a>{% endif %}
            </td>
            <td class="text-right hidden-xs">
              {% if person.photos.all %}
                &nbsp;<span class="glyphicon glyphicon-picture"
                            title="{{ person.photos.count }} Photo{{ person.photos.cout|pluralize }}"></span>
              {% endif %}
              {% if person.notes %}&nbsp;<span class="glyphicon glyphicon-pencil" title="Has Notes"></span>{% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="tab-pane{% if marriages and not births %} active{% endif %}" id="marriages">
      <table class="table" id="marriages-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Husband</th>
            <th>Wife</th>
          </tr>
        </thead>
        <tbody>
        {% for marriage in marriages %}
          <tr>
            <td data-sort-value="{{ marriage.date.lower_bound|date:'Y-m-d' }}">{{ marriage.date.short }}</td>
            <td{% if not marriage.husband.blood_relative %} class="text-muted small"{% endif %}>
              <a href="{% url 'person' marriage.husband.id %}">{{ marriage.husband.birth_name }}</a>
            </td>
            <td{% if not marriage.wife.blood_relative %} class="text-muted small"{% endif %}>
              <a href="{% url 'person' marriage.wife.id %}">{{ marriage.wife.birth_name }}</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="tab-pane{% if deaths and not marriages and not births %} active{% endif %}" id="deaths">
      <table class="table" id="deaths-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Name</th>
            <th class="hidden-xs">Age</th>
            <th class="hidden-xs">Birthplace</th>
            <th class="hidden-xs">&nbsp;</th>
          </tr>
        </thead>
        <tbody>
        {% for person in deaths %}
          <tr{% if not person.blood_relative %} class="text-muted small"{% endif %}>
            <td data-sort-value="{{ person.date_of_death.lower_bound|date:'Y-m-d' }}">{{ person.date_of_death.short }}</td>
            <td><a href="{% url 'person' person.id %}">{{ person.name }}</a></td>
            <td class="hidden-xs">{{ person.age|default_if_none:"Unknown" }}</td>
            <td class="hidden-xs">
              {% if person.birth_location %}
                {% include 'people/fragments/location.html' with location=person.birth_location %}
              {% endif %}
            </td>
            <td class="text-right hidden-xs">
              {% if person.photos.all %}
                &nbsp;<span class="glyphicon glyphicon-picture"
                            title="{{ person.photos.count }} Photo{{ person.photos.cout|pluralize }}"></span>
              {% endif %}
              {% if person.notes %}&nbsp;<span class="glyphicon glyphicon-pencil" title="Has Notes"></span>{% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

people/templates/people/map.html
{% extends "people/base.html" %}
{% load static %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block head %}
  {% include 'people/fragments/mapresources.html' with clustering=True fullscreen=True %}
  <style>
    html {height: 100%;}
    body {margin-top: 60px; height: calc(100% - 60px);}
    #map {height: 100%; padding: 0; margin: 0;}
    .marker-simple div {background-color: #325d88; opacity: 0.84; color: #fff; width: 24px; height: 24px; margin: 12px 0 0 12px;}
    .marker-simple span {line-height: 24px;}
  </style>
{% endblock %}

{% block container %}
  {% include 'people/fragments/map.html' %}
{% endblock %}